# Generated by Django 3.0.5 on 2020-07-01 17:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CIN', models.CharField(max_length=100)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DIN', models.CharField(max_length=200, null=True)),
                ('Name', models.CharField(max_length=200, null=True)),
                ('Begindate', models.DateTimeField(null=True)),
                ('Enddate', models.DateTimeField(null=True)),
                ('SurrenderedDIN', models.CharField(max_length=200, null=True)),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.UserSearches')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CompanyName', models.CharField(max_length=200)),
                ('ROCCode', models.CharField(max_length=200, null=True)),
                ('RegistrationNumber', models.IntegerField(null=True)),
                ('CompanyCategory', models.CharField(max_length=200, null=True)),
                ('CompanySubCategory', models.CharField(max_length=200, null=True)),
                ('ClassofCompany', models.CharField(max_length=200, null=True)),
                ('AuthorisedCapital', models.IntegerField(null=True)),
                ('PaidupCapital', models.IntegerField(null=True)),
                ('NumberofMembers', models.IntegerField(null=True)),
                ('DateofIncorporation', models.DateTimeField(null=True)),
                ('RegisteredAddress', models.CharField(max_length=500, null=True)),
                ('AddressotherthanRo', models.CharField(max_length=500, null=True)),
                ('EmailId', models.EmailField(max_length=254, null=True)),
                ('WhetherListed', models.CharField(max_length=200, null=True)),
                ('ACTIVEcompliance', models.CharField(max_length=200, null=True)),
                ('Suspendedatstockexchange', models.CharField(max_length=200, null=True)),
                ('DateoflastAGM', models.DateTimeField(null=True)),
                ('DateofBalanceSheet', models.DateTimeField(null=True)),
                ('CompanyStatus', models.CharField(max_length=200, null=True)),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companydetail', to='companies.UserSearches')),
            ],
        ),
        migrations.CreateModel(
            name='Charges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Assetsundercharge', models.CharField(max_length=500, null=True)),
                ('ChargeAmount', models.IntegerField(null=True)),
                ('DateofCreation', models.DateTimeField(null=True)),
                ('DateofModification', models.DateTimeField(null=True)),
                ('Status', models.CharField(max_length=200, null=True)),
                ('CIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='companies.UserSearches')),
            ],
        ),
    ]
