# Generated by Django 3.0.5 on 2020-07-02 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='ChargeAmount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='AuthorisedCapital',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='PaidupCapital',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='RegistrationNumber',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
