# Generated by Django 3.0.5 on 2020-07-02 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_auto_20200702_1218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='charges',
            old_name='CIN',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='directors',
            old_name='CIN',
            new_name='company',
        ),
        migrations.AddField(
            model_name='companydetail',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='companydetail', to='companies.UserSearches'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='companydetail',
            name='CIN',
            field=models.CharField(max_length=200),
        ),
    ]
