# Generated by Django 3.0.5 on 2020-07-02 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_auto_20200702_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charges',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='companies.CompanyDetail'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.CompanyDetail'),
        ),
    ]
