# Generated by Django 3.0.5 on 2020-07-04 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20200703_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinmodel',
            name='type',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='charges',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='companies.CompanyDetail'),
        ),
        migrations.AlterField(
            model_name='directors',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.CompanyDetail'),
        ),
        migrations.CreateModel(
            name='LLPDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LLPIN', models.CharField(max_length=200, null=True)),
                ('LLPName', models.CharField(max_length=400, null=True)),
                ('NumberofPartners', models.IntegerField(null=True)),
                ('NumberofDesignatedPartners', models.IntegerField(null=True)),
                ('ROCCode', models.CharField(max_length=200, null=True)),
                ('DateofIncorporation', models.DateTimeField(null=True)),
                ('RegisteredAddress', models.CharField(max_length=500, null=True)),
                ('EmailId', models.EmailField(max_length=254, null=True)),
                ('Previousfirm', models.CharField(max_length=400, null=True)),
                ('TotalObligationofContribution', models.FloatField(null=True)),
                ('MaindivisionofbusinessactivityinIndia', models.CharField(max_length=200, null=True)),
                ('Descriptionofmaindivision', models.CharField(max_length=500, null=True)),
                ('DateofAccountsSolvencyfiled', models.DateTimeField(null=True)),
                ('DateofAnnualReturnfiled', models.DateTimeField(null=True)),
                ('LLPStatus', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llpdetail', to='companies.CinModel')),
            ],
        ),
        migrations.CreateModel(
            name='ForeignCompanyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FCRN', models.CharField(max_length=200, null=True)),
                ('CompanyName', models.CharField(max_length=400, null=True)),
                ('DateofIncorporation', models.DateTimeField(null=True)),
                ('CountryofIncorporation', models.CharField(max_length=200, null=True)),
                ('RegisteredAddress', models.CharField(max_length=500, null=True)),
                ('EmailId', models.EmailField(max_length=254, null=True)),
                ('ForeignCompanywithShareCapital', models.CharField(max_length=200, null=True)),
                ('CompanyStatus', models.CharField(max_length=200, null=True)),
                ('TypeofOffice', models.CharField(max_length=200, null=True)),
                ('Details', models.CharField(max_length=500, null=True)),
                ('MaindivisioninIndia', models.CharField(max_length=200, null=True)),
                ('Descriptionofmaindivision', models.CharField(max_length=200, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='foreigncompanydetail', to='companies.CinModel')),
            ],
        ),
        migrations.AddField(
            model_name='charges',
            name='foreigncompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='companies.ForeignCompanyDetail'),
        ),
        migrations.AddField(
            model_name='charges',
            name='llp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='companies.LLPDetails'),
        ),
        migrations.AddField(
            model_name='directors',
            name='foreigncompany',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.ForeignCompanyDetail'),
        ),
        migrations.AddField(
            model_name='directors',
            name='llp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='directors', to='companies.LLPDetails'),
        ),
    ]
